name: "Check Scala CLA"
on:
  pull_request:
jobs:
  cla-check:
    runs-on: ubuntu-latest
    steps:
      - name: Verify CLA
        uses: scala/cla-checker@v1
        with:
          author: ${{ github.event.pull_request.user.login }}
